# Generated by Django 4.0.1 on 2022-03-29 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_image_created_on_image_title_remove_image_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('thumbnail', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='collections',
            field=models.ManyToManyField(related_name='category', to='portfolio.Collection'),
        ),
        migrations.AddField(
            model_name='image',
            name='collection',
            field=models.ManyToManyField(related_name='posts', to='portfolio.Collection'),
        ),
    ]
